[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm install -g corepack@latest",
  "corepack enable",
  "corepack prepare pnpm@11.11.0 --activate",
  "pnpm i --frozen-lockfile"
]
